name: Deploy Platformatic application to the cloud
on:
  push:
    branches:
      - main
      - wip
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  build_and_deploy:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    env:
     DATABASE_URL: ${{ secrets.DATABASE_URL }}
     PLT_SERVER_LOGGER_LEVEL: info 
     PORT: 3042 
     PLT_SERVER_HOSTNAME: 127.0.0.1 
     PLT_TELEGRAM_BOT_TOKEN: ${{ secrets.PLT_TELEGRAM_BOT_TOKEN }}
     PLT_JWT_SECRET: ${{ secrets.PLT_JWT_SECRET }}
     PLT_BASE_URL: ${{ secrets.PLT_BASE_URL }}
     PLT_GCP_CREDENTIALS: ${{ secrets.PLT_GCP_CREDENTIALS }}

    steps:
      - name: Checkout application project repository
        uses: actions/checkout@v3
      - name: npm install --omit=dev
        run: npm install --omit=dev
      - name: Deploy project
        uses: platformatic/onestep@latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          platformatic_workspace_id: ${{ secrets.PLATFORMATIC_STATIC_WORKSPACE_ID }}
          platformatic_workspace_key: ${{ secrets.PLATFORMATIC_STATIC_WORKSPACE_API_KEY }}
          platformatic_config_path: ./platformatic.db.json
